# Generated by Django 4.0 on 2021-12-30 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enhancement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(max_length=30)),
                ('effect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jutsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sorting_name', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='jutsu/images')),
                ('chacra', models.CharField(choices=[('FO', 'Força'), ('DE', 'Destreza'), ('CO', 'Constituição'), ('IN', 'Inteligência'), ('SA', 'Sabedoria'), ('CA', 'Carisma')], default='FO', max_length=2)),
                ('descriptor', models.CharField(choices=[('AB', 'Abjuração'), ('AD', 'Advinhação'), ('EM', 'Elemental'), ('AC', 'Ácido'), ('EL', 'Eletricidade'), ('FO', 'Fogo'), ('FR', 'Frio'), ('VE', 'Vento'), ('EN', 'Encantamento'), ('IL', 'Ilusão'), ('IN', 'Invocação'), ('NI', 'Ninja'), ('LU', 'Luz'), ('TR', 'Transmutação'), ('TT', 'Trevas'), ('VA', 'Vácuo')], default='AB', max_length=2)),
                ('descriptor2', models.CharField(blank=True, choices=[('AB', 'Abjuração'), ('AD', 'Advinhação'), ('EM', 'Elemental'), ('AC', 'Ácido'), ('EL', 'Eletricidade'), ('FO', 'Fogo'), ('FR', 'Frio'), ('VE', 'Vento'), ('EN', 'Encantamento'), ('IL', 'Ilusão'), ('IN', 'Invocação'), ('NI', 'Ninja'), ('LU', 'Luz'), ('TR', 'Transmutação'), ('TT', 'Trevas'), ('VA', 'Vácuo')], default='', max_length=2)),
                ('grade', models.CharField(choices=[('BA', 'Básico'), ('ME', 'Mediano'), ('AV', 'Avançado'), ('SU', 'Sublime'), ('LE', 'Lendário')], default='BA', max_length=2)),
                ('execution', models.TextField()),
                ('range', models.TextField()),
                ('target_area_effect', models.TextField()),
                ('duration', models.TextField()),
                ('resistance', models.TextField(blank=True)),
                ('description', models.TextField(default='')),
                ('short_description', models.CharField(blank=True, max_length=100)),
                ('book_magazine', models.CharField(blank=True, default='Manual Básico', max_length=100)),
                ('enhancements', models.ManyToManyField(blank=True, related_name='jutsu', to='jutsu.Enhancement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='enhancement',
            name='related_jutsu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jutsu.jutsu'),
        ),
    ]
