# Generated by Django 4.0 on 2021-12-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jutsu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jutsu',
            name='descriptor3',
            field=models.CharField(blank=True, choices=[('AB', 'Abjuração'), ('AD', 'Advinhação'), ('EM', 'Elemental'), ('AC', 'Ácido'), ('EL', 'Eletricidade'), ('FO', 'Fogo'), ('FR', 'Frio'), ('VE', 'Vento'), ('EN', 'Encantamento'), ('IL', 'Ilusão'), ('IN', 'Invocação'), ('NI', 'Ninja'), ('LU', 'Luz'), ('TR', 'Transmutação'), ('TT', 'Trevas'), ('VA', 'Vácuo')], default='', max_length=2),
        ),
    ]
