# Generated by Django 4.0 on 2021-12-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jutsu', '0002_jutsu_descriptor3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jutsu',
            name='grade',
            field=models.CharField(choices=[('BA', 'Básico'), ('ME', 'Mediano'), ('AV', 'Avançado'), ('SU', 'Sublime'), ('LE', 'Lendário')], default='ME', max_length=2),
        ),
    ]
