# Generated by Django 4.0 on 2022-01-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jutsu', '0003_alter_jutsu_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jutsu',
            name='user',
            field=models.ForeignKey(default='admin', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
